[features]
seeds = false
[programs.devnet]
counter = "5iyjRD5AXSeu3EKGcqoE6RHGZk44EkJYw8bacwACmzEL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/loser/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
